export default {
  //aster

  YWAIT_LOGO: require('../../assets/images/ywaitSplashLogo.jpg'),
  ASTER_LOGO: require('../../assets/images/aster/asterLogo.png'),
  ALNOOR_LOGO: require('../../assets/images/alNoor/alnoorLogo.png'),
  INSTA_LOGO : require('../../assets/images/instaLogo.png'),
  //Login left icon
  LOGIN_LEFT_IMAGE: require('../../assets/images/loginImage.png'),
  SETTINGS_GEAR_IMAGE: require('../../assets/images/settingIcon.png'),
  HOME_IMAGE: require('../../assets/images/homeIcon.png'),
  YWAIT_SMALL_LOGO: require('./../../assets/images/ywaitLogo.png'),
  BACK_IMAGE: require('./../../assets/images/backArrow.png'),
  TICK_IMAGE: require('./../../assets/images/tickIcon.png'),
  TICK: require('./../../assets/images/tick.png'),
  TOGGLE_SWITCH_ON: require('./../../assets/images/toggleswitchon.png'),
  TOGGLE_SWITCH_OFF: require('./../../assets/images/toggleswitchoff.png'),
  WHITE_TICK: require('./../../assets/images/whitetick.png'),
  TICK_Round: require('./../../assets/images/tickround.png'),
  LOGIN_BACKGROUND_IMAGE: require('../../assets/images/loginBgImage.png'),
  SPLIT_SCREEN_ICON: require('../../assets/images/splitScreenIcon.png'),
  TV_POINT_ICON: require('../../assets/images/tvPointIcon.png'),
  LOGOUT_ICON: require('../../assets/images/logoutIcon.png'),
  SETTINGS_SELECTED_BG_IMAGE: require('../../assets/images/selectionHighlightBG.png'),
  SPLIT_SCREEN_OPTION_FOCUSED: require('../../assets/images/splitScreenOptionFocusedIcon.png'),
  SPLIT_SCREEN_OPTION_NON_FOCUSED: require('../../assets/images/splitScreenOptionNonFocusedIcon.png'),
  TV_POINT_OPTION_FOCUSED: require('../../assets/images/tvPointOptionFocusedBGIcon.png'),
  TV_POINT_OPTION_NON_FOCUSED: require('../../assets/images/tvPointOptionNonFocusedBGIcon.png'),
  RADIO_ON_ICON: require('../../assets/images/radioOnIcon.png'),
  RADIO_OFF_ICON: require('../../assets/images/radioOffIcon.png'),
  TRANSPARENT_IMAGE: require('../../assets/images/transparentImage.png'),
  LANGUAGE_ICON: require('../../assets/images/language.png'),
  NO_INTERNET: require('../../assets/images/no-signal.png'),
  RIGHT_ARROW : require('../../assets/images/right_arrow.png'),
  MENU_ICON: require('../../assets/images/hambergerIcon.png'),
  // Animations
  NO_APPOINTMENT_ANIMATION: require('../../assets/animations/slotFullAnimation.json'),
  NO_APPOINTMENT: require('../../assets/images/noAppointments.png'),
  EMPTY_CUSTOMER: require('../../assets/images/emptyCustomer.png'),
};
